### ISSUE TITLE
Making sure the target database is saturated

### ISSUE THREAD

**Issue by johto** [trustly/pg_trivialreplay#4]
Right now the process is synchronous: decode transaction, write to the target database.  This doesn't saturate the backend process on the target well enough.  We should be decoding transactions into a buffer of some kind and making sure something is being replayed all the time.

**Comment by mhagander** [comment]
A simple start of this might be to use the libpq async API, so instead of PQexec we issue a PQsendQuery() and the next time we want to do something (whatever it is) we wait for the previous query to finish? That won't make it "entirely" async, but it lets us proceed with other things such as decoding or waiting for network I/O from the sender while the database is processing our commands.

It would probably be fairly easy to implement, unlike "fully async" which would be a lot more work. At least worth a try initially, perhaps?

**Comment by mhagander** [comment]
AFAICT it was easy to implement, attempt done in pull request #7. Needs review of course, it might not be Quite That Simple (TM).

**Comment by mhagander** [comment]
Well, async query is implemented. Let's see if it's enough.

**Comment by johto** [comment]
Either 9.6 is much faster or this has fixed the problem.

**Comment by johto** [comment]
.. or I spoke way too soon.
